require("prototypes.red_science")
require("prototypes.green_science")
require("prototypes.grey_science")
require("prototypes.blue_science")
require("prototypes.purple_science")
require("prototypes.yellow_science")
require("prototypes.technology")